apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkprojects.corp.com
spec:
  group: corp.com
  names:
    kind: xkproject
    plural: xkprojects
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Name of the app project, a new namespace will be created with this name.