apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider
  namespace: crossplane-system
spec:
  projectID: "PROJECT_ID"
  credentials:
    source: AccessToken
    secretRef:
      namespace: crossplane-system
      name: gcp-auth
      key: access-token